    name: Deploy Supabase Functions

    on:
      push:
        branches:
          - main  # ou a branch que você usa como principal (ex: master)
      workflow_dispatch:

    jobs:
      deploy-functions:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Setup Supabase CLI
            uses: supabase/setup-cli@v1
            with:
              version: latest

          - name: Deploy Edge Functions
            run: |
              supabase functions deploy --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} --no-verify-jwt
            env:
              SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}